name: show_more_text_popup
description: A Flutter plugin to show the extra text as a popup with parameters to configure the size and other behavior
version: 0.1.0
author: Sanjay Sharma
homepage: https://github.com/snj07/flutter_show_more_text_popup

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.snj07.show_more_text_popup
        pluginClass: ShowMoreTextPopupPlugin
      ios:
        pluginClass: ShowMoreTextPopupPlugin